export type JobStatus = 'pending' | 'done' | 'as';
export type PhotoGroup = 'before' | 'after';
export type CostItem = { id: string; name: string; amount: number };
export type CommissionItem = { id: string; name: string; amount: number };
export type JobPhoto = { id: string; url: string; storagePath: string; group: PhotoGroup; createdAt: number };
export type Job = {
  id: string;
  ownerId: string;
  clientName: string;
  clientPhone?: string;
  clientCompany?: string;
  address: string;
  addressDetail?: string;
  locationMemo?: string;
  workDate: string;
  status: JobStatus;
  leakType: string;
  beforeNote?: string;
  actionNote?: string;
  afterNote?: string;
  expertOpinion?: string;
  costItems: CostItem[];
  commissions: CommissionItem[];
  photos: JobPhoto[];
  memo?: string;
  createdAt: number;
  updatedAt: number;
};
export type Client = { id: string; ownerId: string; name: string; contact?: string; phone?: string; address?: string; commissionRate?: number; memo?: string; createdAt: number; updatedAt: number };
export type Company = {
  id: string;
  ownerId: string;
  name?: string;
  ceo?: string;
  regNo?: string;
  tel?: string;
  address?: string;
  bank?: string;
  account?: string;
  holder?: string;
  stampUrl?: string;
  stampPath?: string;
  signatureUrl?: string;
  signaturePath?: string;
  bizRegUrl?: string;
  bizRegPath?: string;
  updatedAt: number;
};
